film/urls.py
from django.conf.urls import url

from . import views

app_name = 'film'
urlpatterns = [
	url(r'^$', views.index, name = 'index'),
	url(r'^list/$', views.fullList.as_view(), name = 'list'),
    url(r'^result/$', views.result, name = 'result'),
	url(r'^detail/(?P<title>.+)/$', views.detail, name = 'detail'),
]

uber_challenge/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^film/', include('film.urls')),
    url(r'^admin/', admin.site.urls),
]

film/models.py
from __future__ import unicode_literals

from django.db import models
from mongoengine import *

# Create your models here.
class Film(Document):
    title = StringField(required=True)
    year = IntField()
    locations = StringField(max_length=200)
    company = StringField(max_length=100)
    distributor = StringField(max_length=100)
    director = StringField(max_length=50)
    writer = StringField(max_length=50)
    actor_1 = StringField(max_length=50)
    actor_2 = StringField(max_length=50)
    actor_3 = StringField(max_length=50)
    funfacts = StringField()

    def __str__(self):
        return self.title;

film/views.py
from django.shortcuts import render
from django.views import generic
from pymongo import MongoClient
from film.models import Film

# Create your views here.
def index(request):
    return render(request, 'film/index.html');

class fullList(generic.ListView):
    template_name = 'film/list.html'
    context_object_name = 'film_name_list'

    def get_queryset(self):
        # client = MongoClient()
        # db = client.uber_challenge
        # coll = db.film
        return Film.objects.distinct('title').order_by('title')

def detail(request, title):
    # client = MongoClient()
    # db = client.uber_challenge
    # coll = db.film
    query = title
    film_detail = Film.objects.filter(title=query)[0]
    film_locations = Film.objects.filter(title=query).distinct('locations')
    return render(request, 'film/detail.html', {'film_detail': film_detail, 'film_locations': film_locations})

def result(request):
    # client = MongoClient()
    # db = client.uber_challenge
    # coll = db.film
    query = request.GET ['search_film_name']
    results = Film.objects.filter(title=query).distinct('title').order_by('title')

    return render(request, 'film/result.html', {'results': results})

film/templates/film/detail.html
{% if film_detail %}
  <h1>{{ film_detail.title }}</h1>

  <ul>
    <li>Release Year: {{ film_detail.year }}</li>
    <li>Production Company: {{ film_detail.company }}</li>
    <li>Distributor: {{ film_detail.distributor }}</li>
    <li>Writer: {{ film_detail.writer }}</li>
    <li>Director: {{ film_detail.director }}</li>
    <li>Actors:
      <ul>
        {% if film_detail.actor_1 %}
          <li>{{ film_detail.actor_1 }}</li>
        {% endif %}
        {% if film_detail.actor_2 %}
          <li>{{ film_detail.actor_2 }}</li>
        {% endif %}
        {% if film_detail.actor_3 %}
          <li>{{ film_detail.actor_3 }}</li>
        {% endif %}
      </ul>
    </li>
    <li>Fun Facts: {{ film_detail.funfacts }}</li>
  </ul>
{% endif %}


<h4>Film Locations in SF</h4>
{% if film_locations %}
  <ul>
  {% for location in film_locations %}
    <li>{{ location }}</li>
  {% endfor %}
  </ul>
{% else %}
  <blockquote><p>No Locations are available.</p></blockquote>
{% endif %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

film/templates/film/index.html
{% load staticfiles %}

<link rel = "stylesheet" type = "text/css" href = "{% static 'film/index.css' %}" />

<center>
  <h1>Welcome to SF Film Locations</h1>
</center>

<center>
  <form type="GET" action="{% url 'film:result' %}">
      <input type="text" name="search_film_name"  placeholder="Search By Film Name" >
      <br>
      <button type="submit" >Submit</button>
  </form>

  <a href = "{% url 'film:list' %}">View Full List</a>
</center>

film/templates/film/list.html
<h1>Full Film List</h1>

{% if film_name_list %}
  <ul>
  {% for film_name in film_name_list %}
    <li><a href = "{% url 'film:detail' film_name %}">{{ film_name }}</a></li>
  {% endfor %}
  </ul>
{% else %}
  <p>No films are available.</p>
{% endif %}

film/templates/film/result.html
{% if results %}
  <h1>Result List</h1>

  <ul>
  {% for result in results %}
    <li><a href = "{% url 'film:detail' result.title %}">{{ result.title }}</a></li>
  {% endfor %}
  </ul>

{% else %}
  <h1>No result found</h1>
{% endif %}